# Yarn v2 Configuration
#
# References:
#
# - https://yarnpkg.com/configuration/yarnrc

defaultSemverRangePrefix: ''

enableInlineBuilds: true

nodeLinker: node-modules

nmHoistingLimits: dependencies

npmPublishAccess: public

npmPublishRegistry: https://npm.pkg.github.com

npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: ${PAT_GPR}

  //registry.npmjs.org:
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN}

  //registry.yarnpkg.org:
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN}

npmRegistryServer: https://registry.yarnpkg.com

npmScopes:
  flex-development:
    npmAlwaysAuth: true
    npmAuthToken: ${PAT_GPR}
    npmRegistryServer: https://npm.pkg.github.com

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.0.2.cjs
