# Lock Inactive Threads
#
# References:
#
# - https://github.com/dessant/lock-threads

---
name: lock-inactive-threads
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - id: lock-threads
        name: Lock inactive issues and pull requests
        uses: dessant/lock-threads@v2
        with:
          github-token: ${{ github.token }}
          issue-lock-comment: >
            This issue has been automatically locked since there has not been
            any recent activity after it was closed. Please open a new issue for
            related bugs or features. Be sure to reference this issue.
          issue-lock-inactive-days: 30
          pr-lock-comment: >
            This pull request has been automatically locked since there has not
            been any recent activity after it was closed. Please open a new
            issue for related bugs or features. Be sure to reference this issue.
          pr-lock-inactive-days: 30
